### ISSUE TITLE
Add Form Elements

### ISSUE THREAD

**Issue by mdespuits** [cision/rover-ui#168]
We currently still depend on our internal `@trendkite/ui` library for form elements. Here are some form/input elements

* `Input` (see [Add Form Elements (Input)](https://github.com/cision/rover-ui/issues/281)).
* `Radio`
* `Checkbox`
* `MultiLine`
* `Select`
* `TextArea`
* `Label`

**Comment by mikemfleming** [comment]
I can get started on this one as I already have some proof of concept components made for some project work. I'll take what I have from there and refine them.

**Comment by wendigolabs** [comment]
We might could break this one up by widget since there's a lot of work here.  Perhaps we could split or collaborate on some of this, @mikemfleming?  I had a few ideas on possible enhancements to at least the ```Input``` widget, which I'd like to work on.  I added the following to the channel but I'll put it here.

My ```Input``` idea involves, as the issue directs, some roverification of the ```tk-ui``` version, which does quite a bit, but might could be cleaned up and I’m not sure it supports the full-on range of HTML 5 input options. That would probably be a desirable enhancement.  One major thing I think we could add is validation via Formik/Yup or this other react field validation package.  

Formik, with or without Yup, seems to be the most comprehensive package though at my last gig I did some implementations and evaluation of react-simple-validator and react-form-validator.  I think we could do some neato things by adding validation.

Ideas are appreciated.

**Comment by mikemfleming** [comment]
Awesome! Yeah I'd love some help with the inputs. I've mainly been working on the Form itself, very much based around how Formik works. Here's a snippet from a test to show how it's used:
```
+const renderForm = (props = defaultProps) =>
+  render(
+    <Form {...defaultProps} {...props}>
+      {({ formValues, formState, handleChange, handleBlur, handleCustom }) => (
+        <>
+          <pre data-qa="form-data">
+            {JSON.stringify({ formValues, formState })}
+          </pre>
+          <input
+            data-qa="text-input"
+            type="text"
+            name="textInput"
+            value={formValues.textInput}
+            onChange={handleChange}
+            onBlur={handleBlur}
+          />
+          <input
+            data-qa="radio-input"
+            type="radio"
+            name="radioInput"
+            onChange={handleChange}
+            checked={formValues.radioInput}
+          />
+          <input
+            data-qa="checkbox-input"
+            type="checkbox"
+            name="checkboxInput"
+            onChange={handleChange}
+            checked={formValues.checkboxInput}
+          />
+          {props.onCustom && (
+            <button
+              data-qa="custom-button"
+              onClick={handleCustom(
+                props.onCustom.fieldName,
+                props.onCustom.callback,
+              )}
+            >
+              Evolve it!
+            </button>
+          )}
+          <button data-qa="submit-button" type="submit">
+            Submit
+          </button>
+        </>
+      )}
+    </Form>,
+  );
```

**Comment by wendigolabs** [comment]
Yeah, I liked it's flexibility.  Have you any opinions on Yup?

**Comment by mikemfleming** [comment]
I haven't used it but IIRC it's what they recommend using and looks very similar to some other schema validation libs I've used before like JOI or AJV. 

I really like how you can use whatever validation you want though. In the feature I'm working on for my team I just use callbacks instead of any of the above tech and it's really nice.
