### ISSUE TITLE
TabMenu makes changing defaults tricky

### ISSUE THREAD

**Issue by mdespuits** [cision/rover-ui#218]
By default, the `TabMenu` component does _not_ include styles. I think this may cause more harm than good. If you are using the `EasyTabMenu`, these styles are applied by default. However, if you construct your own `TabMenu` component to have full control it does not apply styles to tab items.

This makes sense at some level. The styles or tab menu items are applied to _children_ of `TabMenu.Item`s. This may be buttons, spans, or anchors. We may have different treatments for each. However, the suggested `itemPadding` name to apply is misleading as it also adds several other styles including background-color.

It may be worth applying these by default **or** providing better documentation on how to set the styles of tab menu items. Thoughts?

**Comment by pixelbandito** [comment]
Yeah, this is a little convoluted.

Ideally, we wouldn't add any extra wrappers we don't need. Maybe `TabMenu.Item` could be a thinner wrapper, and not add a wrapping element at all unless its children is just a text node. For React components as children, we could maybe iterate over them and just add the relevant classes and click handlers.

That could make it easier for consumers to understand, getting rid of some unpredictable styles due to wrapping custom contents in an extra styled div.

If `EasyTabMenu` does everything necessary and allows sufficient customization, I think I'd prefer to encourage ppl to use it instead of building their own. Maybe we should add a note to the docs pointing to `Easy*` components from their not-easy counterparts.

Agree that we'd still want better documentation for the base `TabMenu` so people know how to use it in the cases where it's really necessary.
